# Generated by Django 2.2.12 on 2021-05-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCompressor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='aFEpSrsdmW', max_length=225)),
                ('image_file', models.ImageField(upload_to='image-compressed')),
            ],
        ),
    ]
