# Generated by Django 2.2.12 on 2021-05-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecompressor',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_name',
            field=models.CharField(default='weUnbqFoBR', max_length=225),
        ),
    ]
