# Generated by Django 2.2.12 on 2021-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0005_auto_20210506_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_file',
            field=models.ImageField(upload_to='image-compress', verbose_name='Mage'),
        ),
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_name',
            field=models.CharField(default='kYGuztrGcm', max_length=225),
        ),
    ]
