# Generated by Django 2.2.12 on 2021-05-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0006_auto_20210506_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_file',
            field=models.ImageField(upload_to='image-compress'),
        ),
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_name',
            field=models.CharField(default='APcxvbWppx', max_length=225),
        ),
    ]
