# Generated by Django 2.2.12 on 2021-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0008_auto_20210506_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_name',
            field=models.CharField(default='cMRwqdhsbi', max_length=225),
        ),
    ]
