# Generated by Django 2.2.12 on 2021-05-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0011_auto_20210506_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_name',
            field=models.CharField(default='hSgLHYkYiT', max_length=225),
        ),
    ]
