# Generated by Django 2.2.12 on 2021-05-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0012_auto_20210506_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_name',
            field=models.CharField(default='ARGCoSPygB', max_length=225),
        ),
    ]
