# Generated by Django 2.2.12 on 2021-05-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0014_auto_20210507_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_name',
            field=models.CharField(default='DHhrtMJElZ', max_length=225),
        ),
    ]
