# Generated by Django 2.2.12 on 2021-05-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0015_auto_20210507_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_name',
            field=models.CharField(default='vhMEJSMFWE', max_length=225),
        ),
    ]
