# Generated by Django 2.2.12 on 2021-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0016_auto_20210507_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompressor',
            name='image_name',
            field=models.CharField(default='wRyRJSpZKJ', max_length=225),
        ),
    ]
